START_QUIZ = 'start_quiz'
HINT = 'hint'
EXIT = 'exit'
ABOUT = 'about'
DIFFICULTY = 'difficulty'

# Default intents
YANDEX_CONFIRM = 'YANDEX.CONFIRM'
YANDEX_REJECT = 'YANDEX.REJECT'
YANDEX_HELP = 'YANDEX.HELP'
YANDEX_REPEAT = 'YANDEX.REPEAT'
YANDEX_WHAT_CAN_YOU_DO = 'YANDEX.WHAT_CAN_YOU_DO'