START_QUIZ = 'start_quiz'
CLUE = 'clue'
EXIT = 'exit'
ABOUT = 'about'
CHANGE_DIFFICULTY = 'difficulty'
GET_LEVEL = 'level'

# Default intents
YANDEX_CONFIRM = 'YANDEX.CONFIRM'
YANDEX_REJECT = 'YANDEX.REJECT'
YANDEX_HELP = 'YANDEX.HELP'
YANDEX_REPEAT = 'YANDEX.REPEAT'
YANDEX_WHAT_CAN_YOU_DO = 'YANDEX.WHAT_CAN_YOU_DO'