name: Run tests

on:
  push:
    branches:
      - master

jobs:
# build grafana image
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.0
        ports:
        - 27017:27017
        command: --storageEngine=wiredTiger
        volumes:
        - /tmp:/data/db
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
      - name: Run tests
        run: |
          cd app/tests && pytest
          
